pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('cilm-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('cilm-service') {
                    sh 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('cilm-service') {
                    sh 'docker build -t cilm-service:latest .'
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker stop cilm-service || true
                    docker rm cilm-service || true

                    docker run -d \
                      --name cilm-service \
                      -p 8081:8081 \
                      cilm-service:latest
                '''
            }
        }
    }

    post {
        success {
            echo 'Build, Test, Docker Build and Deployment completed successfully!'
        }

        failure {
            echo 'Pipeline failed. Check the console output.'
        }
    }
}
