server:
  port: ${SERVER_PORT:9091}

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:9090}
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/inventory/**
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/payments/**

jwt:
  secret: my-very-secret-key-for-demo-only
