spring:
  application:
    name: ${APPLICATION_NAME:zen-cilm-service}

  datasource:
    url: jdbc:mysql://localhost:3306/cilm
    username: root
    password: Shiva@2001
    driver-class-name: com.mysql.cj.jdbc.Driver

    Hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
  shutdown: graceful

logging:
  level:
    root: INFO
    com.zenbank.cilm: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE