spring:
  application:
    name: ${APPLICATION_NAME:zen-cilm-service}

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cilm}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    com.zenbank.cilm: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:DEBUG}
    org.hibernate.orm.jdbc.bind: ${HIBERNATE_BIND_LOG:TRACE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${APPLICATION_NAME:zen-cilm-service}
    version: ${APPLICATION_VERSION:1.0.0}
    environment: ${APP_ENV:local}
